# Generated by Django 5.1.4 on 2024-12-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=100, unique=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('antonyms', models.CharField(default='', max_length=100)),
                ('synonyms', models.CharField(default='', max_length=100)),
                ('example', models.CharField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DictionaryWord',
        ),
    ]
