# Generated by Django 5.1.4 on 2024-12-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='page_title',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
