# Generated by Django 5.1.4 on 2024-12-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_word_delete_dictionaryword'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('descrption', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Word',
            new_name='WordModel',
        ),
    ]
