# Generated by Django 5.1.4 on 2024-12-26 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_footermodel_headermodel_postcategorymodel_postmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategorymodel',
            name='cat_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='postCat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.postcategorymodel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
