# Generated by Django 5.1.4 on 2024-12-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pagemodel_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategorymodel',
            name='cat_order',
            field=models.IntegerField(default=0),
        ),
    ]
