# Generated by Django 5.1.4 on 2024-12-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_postcategorymodel_cat_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='word',
            field=models.CharField(default='', max_length=100),
        ),
    ]
