# Generated by Django 5.1.5 on 2026-03-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blogmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
