# Generated by Django 5.1.4 on 2025-01-02 06:33

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_postcategorymodel_cat_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='page_content',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
