# Generated by Django 5.1.4 on 2025-01-02 06:41

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_pagemodel_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='page_content',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
