# Generated by Django 5.1.4 on 2025-01-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pagemodel_page_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagemodel',
            old_name='page_content',
            new_name='page_description',
        ),
    ]
