# Generated by Django 5.1.4 on 2024-12-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_postmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='descrption',
            new_name='description',
        ),
    ]
