# Generated by Django 5.1.4 on 2025-01-02 10:43

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_pagemodel_page_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='', max_length=100, unique=True)),
                ('blog_description', tinymce.models.HTMLField()),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('author', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
