# Generated by Django 5.1.4 on 2025-01-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_blogmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='author',
            new_name='blog_author',
        ),
    ]
