# Generated by Django 4.2.17 on 2024-12-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_postmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='full_desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
