# Generated by Django 4.2.17 on 2024-12-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_postmodel_full_desc_alter_postmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='icon',
            field=models.CharField(choices=[('fa fa-facebook', 'Facebook'), ('fa fa-twitter', 'Twitter'), ('fa fa-instagram', 'Instagram'), ('fa fa-linkedin', 'LinkedIn')], default='', help_text='Select an icon class.', max_length=50),
        ),
    ]
