# Generated by Django 4.2.17 on 2024-12-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_postmodel_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='icon',
        ),
    ]
