# Generated by Django 4.2.17 on 2024-12-23 06:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_footermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='description',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='full_desc',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
