# Generated by Django 4.2.17 on 2024-12-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_postmodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='', max_length=100)),
                ('logo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='heading',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
