# Generated by Django 4.2.17 on 2024-12-24 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_headermodel_alter_footermodel_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='postmodel',
            name='postCat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='postcategory', to='api.postcategorymodel'),
        ),
    ]
