# Generated by Django 4.2.17 on 2024-12-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_postmodel_postcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategorymodel',
            name='cat_title',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
