# Generated by Django 4.2.17 on 2024-12-24 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_postcategorymodel_cat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='postCat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postcategory', to='api.postcategorymodel'),
        ),
    ]
