# Generated by Django 4.2.17 on 2024-12-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_postmodel_postcat_postmodel_postcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='postCat',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='postCat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='postcategory', to='api.postcategorymodel'),
        ),
    ]
