# Generated by Django 4.2.17 on 2024-12-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_postmodel_postcat_postmodel_postcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='postCat',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='postCat',
            field=models.ManyToManyField(related_name='postcategory', to='api.postcategorymodel'),
        ),
    ]
